#!/bin/sh

mysqldump \
    --skip-opt \
    --allow-keywords \
    --extended-insert \
    --quote-names \
    --create-options \
    --compress \
    --default-character-set=latin1 \
    --add-drop-database \
    --add-drop-table \
    --databases \
    zoesmayr > ../DB/init.sql
